#include "GPUCodeGen.h"

#include "mlir/Support/LogicalResult.h"

#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/raw_ostream.h"

#include <sstream>

namespace qfx {

namespace {

std::string kernelBody(const HirModule &hir) {
  std::ostringstream oss;
  const int64_t n = hir.imports.front().type.length;
  int64_t window = 20;
  for (const auto &binding : hir.bindings) {
    if (binding.window > 0)
      window = binding.window;
  }

  oss << "extern \"C\" __global__ void qfx_kernel(";
  for (size_t i = 0; i < hir.imports.size(); ++i) {
    if (i > 0)
      oss << ", ";
    oss << "const float *" << hir.imports[i].name;
  }
  for (size_t i = 0; i < hir.emits.size(); ++i) {
    oss << ", float *out" << i;
  }
  oss << ", int n, int w) {\n";
  oss << "  int k = blockIdx.x * blockDim.x + threadIdx.x;\n";
  oss << "  if (k >= n) return;\n";

  bool emitsCov = false;
  for (const auto &binding : hir.bindings) {
    if (binding.op == HirOp::RollingCov || binding.op == HirOp::FusedRollingCov)
      emitsCov = true;
  }

  if (emitsCov && hir.imports.size() >= 2) {
    const std::string &a = hir.imports[0].name;
    const std::string &b = hir.imports[1].name;
    oss << "  float sumX = 0.f, sumY = 0.f, sumXY = 0.f;\n";
    oss << "  for (int i = 0; i < w; ++i) {\n";
    oss << "    int j = k - i;\n";
    oss << "    if (j >= 0 && j < n) {\n";
    oss << "      float x = " << a << "[j], y = " << b << "[j];\n";
    oss << "      float inv = 1.f / (float)w;\n";
    oss << "      sumX += x * inv; sumY += y * inv; sumXY += x * y * inv;\n";
    oss << "    }\n";
    oss << "  }\n";
    oss << "  out0[k] = sumXY - sumX * sumY;\n";
  } else {
    const std::string &input = hir.imports[0].name;
    oss << "  float sum = 0.f;\n";
    oss << "  for (int i = 0; i < w; ++i) {\n";
    oss << "    int j = k - i;\n";
    oss << "    if (j >= 0 && j < n) sum += " << input << "[j] / (float)w;\n";
    oss << "  }\n";
    oss << "  out0[k] = sum;\n";
  }

  oss << "}\n\n";
  oss << "extern \"C\" void qfx_launch(";
  for (size_t i = 0; i < hir.imports.size(); ++i) {
    if (i > 0)
      oss << ", ";
    oss << "const float *" << hir.imports[i].name;
  }
  for (size_t i = 0; i < hir.emits.size(); ++i)
    oss << ", float *out" << i;
  oss << ", int n, int w, void *stream) {\n";
  oss << "  int threads = 256;\n";
  oss << "  int blocks = (n + threads - 1) / threads;\n";
  oss << "  qfx_kernel<<<blocks, threads, 0, (cudaStream_t)stream>>>(";
  for (size_t i = 0; i < hir.imports.size(); ++i) {
    if (i > 0)
      oss << ", ";
    oss << hir.imports[i].name;
  }
  for (size_t i = 0; i < hir.emits.size(); ++i)
    oss << ", out" << i;
  oss << ", n, w);\n";
  oss << "}\n";
  return oss.str();
}

} // namespace

std::string generateCudaSource(const HirModule &hir) {
  std::ostringstream oss;
  oss << "// Generated by quantfx-compiler (Phase 2 GPU backend)\n";
  oss << "#include <cuda_runtime.h>\n\n";
  oss << kernelBody(hir);
  return oss.str();
}

mlir::LogicalResult emitCudaKernel(const HirModule &hir, const std::string &outputPath,
                                   bool emitPtx) {
  std::string source = generateCudaSource(hir);
  std::string cuPath = outputPath;
  if (emitPtx && cuPath.size() > 4 && cuPath.substr(cuPath.size() - 4) == ".ptx")
    cuPath = outputPath.substr(0, outputPath.size() - 4) + ".cu";

  std::error_code ec;
  llvm::raw_fd_ostream cuFile(cuPath, ec);
  if (ec)
    return mlir::failure();
  cuFile << source;

  if (!emitPtx)
    return mlir::success();

  std::string error;
  if (!llvm::sys::findProgramByName("nvcc", error)) {
    llvm::errs() << "nvcc not found; wrote CUDA source to " << cuPath << "\n";
    return mlir::success();
  }

  llvm::SmallVector<llvm::StringRef, 8> args;
  args.push_back("nvcc");
  args.push_back("-ptx");
  args.push_back("-O3");
  args.push_back("-o");
  args.push_back(outputPath);
  args.push_back(cuPath);

  std::string stderrMsg;
  int rc = llvm::sys::ExecuteAndWait("nvcc", args, std::nullopt, {}, 0, 0, &stderrMsg);
  if (rc != 0) {
    llvm::errs() << "nvcc failed: " << stderrMsg << "\n";
    return mlir::failure();
  }
  llvm::outs() << "wrote PTX " << outputPath << " (source: " << cuPath << ")\n";
  return mlir::success();
}

} // namespace qfx
